# Generated by Django 5.1.1 on 2024-09-29 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SupportedFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_genre',
            field=models.ManyToManyField(blank=True, to='basic.genre'),
        ),
        migrations.CreateModel(
            name='EPubBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('date_published', models.DateField()),
                ('can_fork', models.BooleanField(default=False)),
                ('ongoing', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='epub_books/')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.supportedformat')),
            ],
        ),
    ]
