# Generated by Django 5.1.1 on 2024-11-09 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_book_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='ongoing',
        ),
        migrations.AddField(
            model_name='book',
            name='ongoing',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Fork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_forked', models.DateField(auto_now_add=True)),
                ('forked_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original', to='basic.book')),
                ('forked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('original_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forks', to='basic.book')),
            ],
        ),
    ]
