# Generated by Django 5.1.1 on 2024-11-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_remove_chapter_ongoing_book_ongoing_fork'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='epub_books/'),
        ),
    ]
