# Generated by Django 5.1.1 on 2024-11-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_book_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='date_published',
            field=models.DateField(auto_now_add=True),
        ),
    ]
