# Generated by Django 5.1.1 on 2024-11-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0007_alter_chapter_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_forked',
            field=models.BooleanField(default=False),
        ),
    ]
