# Generated by Django 5.1.1 on 2024-11-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0008_book_is_forked'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reversed_chapter_order',
            field=models.BooleanField(default=False),
        ),
    ]
